# Generated by Django 5.0.6 on 2024-06-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('emails_count', models.PositiveIntegerField(blank=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('send_time', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('html', models.FileField(blank=True, upload_to='html_emails')),
                ('raw', models.FileField(blank=True, upload_to='emails_raw')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
            ],
        ),
    ]
