# Generated by Django 5.0.6 on 2024-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_mail_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='html',
            field=models.FileField(blank=True, upload_to='media/html_emails'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='raw',
            field=models.FileField(blank=True, upload_to='media/emails_raw'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_time',
            field=models.DateTimeField(),
        ),
    ]
