# Generated by Django 5.0.6 on 2024-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_mail_html_alter_mail_raw_alter_mail_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='send_time',
            field=models.CharField(max_length=255),
        ),
    ]
