# Generated by Django 5.0.6 on 2024-06-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('emails', '0006_maillink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillink',
            name='is_alien',
        ),
        migrations.AlterField(
            model_name='maillink',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='maillink',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='emails.mail'),
        ),
    ]
