# Generated by Django 5.0.6 on 2024-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_mail_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='imap_error',
            field=models.TextField(blank=True),
        ),
    ]
